---
- hosts: all
  vars:
    greeting: Hello!

  tasks:
    - name: make sure apache is installed
      apt: name=apache2 state=present

    - name: configure apache to listen on nonstandard port
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen " line="Listen 80 8080" backup=yes
      notify: restart apache

    - name: make sure apache is started and will be run at boot
      service: name=apache2 state=started enabled=yes

    - name: copy our page to document root
      template: src=index.html.j2 dest=/var/www/html/index.html

    - name: disable selinux
      selinux: policy=targeted state=permissive
      when: ansible_os_family == "RedHat"

    - name: install utilities
      apt: name={{ item }} state=present
      with_items:
      - vim
      - tmux
      - htop
      - tree

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
